repos:
  - repo: https://github.com/Glatzel/template
    rev: v0.0.1
    hooks:
      # pre-commit-hooks
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      #rust
      - id: cargo-clippy
      - id: cargo-fmt
      # python
      - id: ruff-lint
      - id: ruff-format
      - id: numpydoc
      # misc
      - id: taplo
      - id: actionlint
