[workspace]
members = ["./crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.0.34"

[workspace.dependencies]
clerk = { path = "./crates/clerk/", default-features = false }
mischief = { path = "./crates/mischief/" }
mischief-macros = { path = "./crates/mischief-macros/" }
rax = { path = "./crates/rax/", default-features = false }
serialport-ext = { path = "./crates/serialport-ext/" }

async-trait = "0.1.89"
chrono = { version = "0.4.42", default-features = false, features = ["clock"] }
criterion = { package = "codspeed-criterion-compat", version = "4.2.0" }
defmt = "1.0.1"
float-cmp = "0.10.0"
hashbrown = "0.16.0"
owo-colors = "4.2.2"
quote = "1.0.40"
serde = "1.0.219"
serialport = "4.8.1"
supports-color = "3.0.2"
supports-hyperlinks = "3.2.0"
supports-unicode = "3.0.0"
syn = "2.0.111"
terminal_size = "0.4.3"
textwrap = "0.16.2"
thiserror = { version = "2.0.16", default-features = false }
tokio = { version = "1.48.0", default-features = false }
tokio-serial = "5.4.5"
tracing = "0.1.44"
tracing-core = "0.1.36"
tracing-subscriber = "0.3.22"
