fn_single_line = true
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
ignore = ["**/bindings.rs"]
imports_granularity = "Module"
reorder_imports = true
unstable_features = true
wrap_comments = true
