[project]
authors = [{ name = "Glatzel", email = "893016099@qq.com" }]
dependencies = ["lazy-loader", "rich"]
dynamic = ["version"]
name = "toolbox"
requires-python = ">=3.13"

[tool.pyright]
reportShadowedImports = false

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64", "linux-aarch64"]

[tool.pixi.dependencies]
python = "3.13.*"
rattler-build = "==0.53.0"
# test
pyfakefs = "==5.10.2"
pytest = "==9.0.1"
pytest-cov = "==7.0.0"
